# Generated by Django 5.0.2 on 2025-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0004_remove_prototype_port_remove_prototype_running_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prototype",
            name="documentation",
            field=models.TextField(null=True, blank=True, default=""),
        ),
    ]
